# Generated by Django 6.1 on 2026-08-28 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionEntrainement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entrainement', models.DateTimeField(auto_now_add=True)),
                ('periode_train', models.CharField(blank=True, max_length=50)),
                ('periode_test', models.CharField(blank=True, max_length=50)),
                ('meilleur_modele', models.CharField(blank=True, max_length=20)),
                ('explication_meilleur_modele', models.TextField(blank=True)),
                ('est_active', models.BooleanField(default=True, help_text='Session actuellement utilisée pour générer les prévisions.')),
                ('artefacts_pickle', models.BinaryField(blank=True, help_text='Sérialisation des modèles entraînés (usage interne, non exposé côté UI).', null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_entrainement', to='datasets.dataset')),
                ('lance_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'entraînement",
                'verbose_name_plural': "Sessions d'entraînement",
                'ordering': ['-date_entrainement'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(choices=[('XGBoost', 'XGBoost'), ('LightGBM', 'LightGBM'), ('LSTM', 'LSTM'), ('ARIMA', 'ARIMA')], max_length=20)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('r2', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('duree_secondes', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(default='Entraîné', max_length=255)),
                ('est_le_meilleur', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='forecasting.sessionentrainement')),
            ],
            options={
                'verbose_name': 'Évaluation de modèle',
                'verbose_name_plural': 'Évaluations de modèles',
                'constraints': [models.UniqueConstraint(fields=('session', 'nom_modele'), name='unique_evaluation_par_session')],
            },
        ),
    ]
