# Generated by Django 6.1 on 2026-08-28 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée du journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['-horodatage'], name='core_journa_horodat_97448c_idx')],
            },
        ),
    ]
